WITH FECHAS AS (

    SELECT 
        YEAR(CURRENT_DATE) AS A_ACTUAL, 
        YEAR(DATEADD(YEAR, -1, CURRENT_DATE)) AS A_ANTERIOR, 
        DAY(CURRENT_DATE - 1) AS HASTA, 
        MONTH(CURRENT_DATE) AS MES_ACTUAL,
        DAY(DATE_TRUNC(MONTH, CURRENT_DATE())) AS DESDE

) --SELECT * FROM FECHAS;
,

TATA_FISICO AS (

    SELECT 
        YEAR(FFM.TIEM_DIA_ID) AS ANIO,
        MONTH(FFM.TIEM_DIA_ID) AS MES,
        FFM.SOCI_SOCI_ID AS SOCIO,
        FFM.TICKET AS TICKET
    FROM 
        MSTRDB.DWH.FT_FDLN_MOVIMIENTOS AS FFM
        INNER JOIN MSTRDB.DWH.FT_VENTAS AS FV ON FFM.TICKET = FV.TICKET
        JOIN FECHAS AS F
    WHERE 
        YEAR(FFM.TIEM_DIA_ID) IN (F.A_ACTUAL, F.A_ANTERIOR)
        AND FFM.FDLN_MOVT_TIPO = 'RP'
        AND FFM.GEOG_LOCL_ID IN (SELECT DISTINCT GEOG_LOCL_ID FROM MSTRDB.DWH.LU_GEOG_LOCAL WHERE GEOG_UNNG_ID = 2)
        AND FFM.TIEM_DIA_ID < DATE_TRUNC(MONTH, CURRENT_DATE())

) --SELECT * FROM TATA_FISICO LIMIT 10;
,
ECOMMERCE AS (

    SELECT
        YEAR(TRANSACTION_DATE) AS ANIO,
        MONTH(TRANSACTION_DATE) AS MES,
        B.SOCI_SOCI_ID AS SOCIO,
        TICKET_ID AS TICKET
    FROM
        MSTRDB.NPL.MOVEMENTS AS A
        INNER JOIN MSTRDB.DWH.LU_CLIE_CLIENTE AS B ON A.DOCUMENT_TYPE = B.CLIE_TIPO_DOC AND A.DOCUMENT_NUMBER = B.CLIE_CLIE_NDOC
        JOIN FECHAS AS F
    WHERE
        A.MOVEMENT_TYPE = 'EARN'
        AND A.BRANCH_ID = 198
        AND YEAR(TRANSACTION_DATE) IN (F.A_ACTUAL, F.A_ANTERIOR)
        AND TRANSACTION_DATE < DATE_TRUNC(MONTH, CURRENT_DATE())

) --SELECT ANIO, COUNT(DISTINCT(SOCIO)), COUNT(DISTINCT(TICKET)) FROM ECOMMERCE GROUP BY ALL;
,
OMNICANAL AS (
    SELECT  *
    FROM
        (
        (SELECT * FROM TATA_FISICO)
        UNION ALL
        (SELECT * FROM ECOMMERCE)
        )
    
) --SELECT * FROM OMNICANAL;
,
TOTAL_TICKETS_TATA AS (

    SELECT
        YEAR(TIEM_DIA_ID) AS ANIO,
        MONTH(TIEM_DIA_ID) AS MES,
        COUNT(DISTINCT(TICKET)) TICKETS_TATA
    FROM
        MSTRDB.DWH.FT_VENTAS AS A
        INNER JOIN MSTRDB.DWH.LU_GEOG_LOCAL AS B ON A.GEOG_LOCL_ID = B.GEOG_LOCL_ID AND B.GEOG_UNNG_ID = 2
        JOIN FECHAS AS P
    WHERE
        YEAR(TIEM_DIA_ID) IN (P.A_ACTUAL, P.A_ANTERIOR)
        AND TIEM_DIA_ID < DATE_TRUNC(MONTH, CURRENT_DATE())
    GROUP BY 
        ALL
)
,
CLIENTES AS (
    SELECT
        'TATA' AS UNNG,
        O.MES,
        O.ANIO,
        COUNT(DISTINCT(SOCIO)) AS SOCIOS,
        COUNT(DISTINCT(TICKET)) AS TICKETS_FIDELIZADOS,
        TT.TICKETS_TATA,
        ROUND(
            (TICKETS_FIDELIZADOS - LAG(TICKETS_FIDELIZADOS) OVER (PARTITION BY O.MES ORDER BY O.ANIO, O.MES)) / NULLIF(LAG(TICKETS_FIDELIZADOS) OVER (PARTITION BY O.MES ORDER BY O.ANIO, O.MES), 0) * 100, 2
        ) AS VARIACION_TICK,
        ROUND((TICKETS_FIDELIZADOS / TICKETS_TATA) * 100, 2)  AS PORCENTAJE_FIDELIZACION,
        ROUND(
            (PORCENTAJE_FIDELIZACION - LAG(PORCENTAJE_FIDELIZACION) OVER (PARTITION BY O.MES ORDER BY O.ANIO, O.MES)) / NULLIF(LAG(PORCENTAJE_FIDELIZACION) OVER (PARTITION BY O.MES ORDER BY O.ANIO, O.MES), 0) * 100, 2
        ) AS VARIACION_PCT
    FROM
        OMNICANAL AS O
        INNER JOIN TOTAL_TICKETS_TATA AS TT ON O.ANIO = TT.ANIO AND O.MES = TT.MES
    GROUP BY
        ALL
) 

SELECT * FROM CLIENTES ORDER BY MES, ANIO;