WITH PROMOCIONES_ABANDONO AS (

    SELECT
        CAMP_PROM_ID,
        COALESCE(PAZOS_CODIGO_PROMO, VNTA_CODIGO_PROMOCION) AS VNTA_CODIGO_PROMOCION,
        GEO_PROMOTION,
        CAMP_PROM_FINI,
        CAMP_PROM_FFIN,
        CAMP_PROM_UNNG,
        CAMP_PROM_TIPO,
        CAMP_PROM_NOMBRE,
        CAMP_PROM_ESPECIFICACION,
        CAMP_PROM_OBJETIVO,
        CAMP_PROM_APLICACION,
        CAMP_PROM_CANAL
    FROM
        SANDBOX_PLUS.DWH.DETALLE_PROMO AS A
        LEFT JOIN MSTRDB.DWH.LU_PROMO_RPM AS L on L.RPM_CODIGO_PROMO = A.VNTA_CODIGO_PROMOCION
    WHERE
        CAMP_PROM_OBJETIVO <> 'Informativo'
        AND CAMP_PROM_NOMBRE ILIKE '%ABANDO%'
        AND YEAR(CAMP_PROM_FINI) >= YEAR(CURRENT_DATE) - 1
    ORDER BY
        CAMP_PROM_ID DESC

) 
,

IMPACTADOS AS (

    SELECT
        CAMP_PROM_ID,
        COUNT(DISTINCT(SOCI_SOCI_ID)) IMPACTADOS
    FROM
        SANDBOX_PLUS.DWH.DETALLE_CLIENTES
    WHERE
        CAMP_PROM_ID IN (SELECT DISTINCT CAMP_PROM_ID FROM PROMOCIONES_ABANDONO)
    GROUP BY
        ALL
    ORDER BY
        CAMP_PROM_ID DESC
        

) 
,
TICKETS_TOTAL AS (

    SELECT
        DISTINCT
        TIEM_DIA_ID,
        VNTA_COD_DESCUENTO,
        TICKET,
        CAMP_PROM_ID,
        CAMP_PROM_NOMBRE,
        CAMP_PROM_ESPECIFICACION,
        CAMP_PROM_FINI,
        CAMP_PROM_FFIN,
        CAMP_PROM_UNNG,
        CAMP_PROM_CANAL,
        B.VNTA_CODIGO_PROMOCION
    FROM
        MSTRDB.DWH.FT_VENTAS_DESCUENTOS_LINEAS A
         INNER JOIN PROMOCIONES_ABANDONO B ON (
                A.VNTA_COD_DESCUENTO::VARCHAR = B.VNTA_CODIGO_PROMOCION 
                OR A.VNTA_CODIGO_PROMOCION::VARCHAR = B.VNTA_CODIGO_PROMOCION
                OR A.VNTA_CODIGO::VARCHAR = B.VNTA_CODIGO_PROMOCION
                OR A.VNTA_COD_DESCUENTO::VARCHAR = B.GEO_PROMOTION AND B.GEO_PROMOTION IS NOT NULL
                OR A.VNTA_CODIGO_PROMOCION::VARCHAR = B.GEO_PROMOTION AND B.GEO_PROMOTION IS NOT NULL
                OR A.VNTA_CODIGO::VARCHAR = B.GEO_PROMOTION AND B.GEO_PROMOTION IS NOT NULL
            ) AND A.TIEM_DIA_ID BETWEEN B.CAMP_PROM_FINI AND B.CAMP_PROM_FFIN
    WHERE
        YEAR(TIEM_DIA_ID) >= YEAR(CURRENT_DATE) - 1
        AND B.CAMP_PROM_APLICACION = 'Total'

) 
,
ACCION_ABANDONO_TOTAL AS (
    SELECT
        'ABANDONO' AS ACCION,
        'REACTIVACION CLIENTES' AS OBJETIVO,
        YEAR(FV.TIEM_DIA_ID) ANIO,
        MONTH(FV.TIEM_DIA_ID) AS MES,
        COUNT(DISTINCT(FV.TICKET)) AS TICKETS,
        ROUND(SUM(FV.VNTA_IMPORTE_SIN_IVA)) AS VTA_PROMO,
        ROUND(SUM(FV.VNTA_IMPORTE_SIN_IVA - (FV.VNTA_UNIDADES * FV.VNTA_COSTO_PROM_POND))) AS GB1_PROMO,
        ROUND(GB1_PROMO / VTA_PROMO, 2) AS MARGEN_PROMO,
        COUNT(DISTINCT(FFM.SOCI_SOCI_ID)) AS SOCIOS_CON_PROMO
    FROM
        MSTRDB.DWH.FT_VENTAS AS FV
        INNER JOIN MSTRDB.DWH.FT_FDLN_MOVIMIENTOS AS FFM ON FV.TICKET = FFM.TICKET AND FV.TIEM_DIA_ID = FFM.TIEM_DIA_ID
    WHERE
        YEAR(FV.TIEM_DIA_ID) >= YEAR(CURRENT_DATE) - 1
        AND FFM.FDLN_MOVT_TIPO = 'RP'
        AND FV.TICKET IN (SELECT DISTINCT TICKET FROM TICKETS_TOTAL)
    GROUP BY
        ALL
ORDER BY
    1 DESC,
    2,
    3
) 

,
PROMOCIONES_FOCO_NOABANDONO AS (

    SELECT
        CAMP_PROM_ID,
        COALESCE(PAZOS_CODIGO_PROMO, VNTA_CODIGO_PROMOCION) AS VNTA_CODIGO_PROMOCION,
        GEO_PROMOTION,
        CAMP_PROM_FINI,
        CAMP_PROM_FFIN,
        CAMP_PROM_UNNG,
        CAMP_PROM_TIPO,
        CAMP_PROM_NOMBRE,
        CAMP_PROM_ESPECIFICACION,
        CAMP_PROM_OBJETIVO,
        CAMP_PROM_APLICACION,
        CAMP_PROM_CANAL
    FROM
        SANDBOX_PLUS.DWH.DETALLE_PROMO AS A
        LEFT JOIN MSTRDB.DWH.LU_PROMO_RPM AS L on L.RPM_CODIGO_PROMO = A.VNTA_CODIGO_PROMOCION
    WHERE
        CAMP_PROM_OBJETIVO <> 'Informativo'
        AND YEAR(CAMP_PROM_FINI) >= YEAR(CURRENT_DATE) - 1
        AND (CAMP_PROM_NOMBRE ILIKE '%FRECUENCIA%' OR CAMP_PROM_NOMBRE ILIKE 'LOCALES EN FOCO' OR CAMP_PROM_NOMBRE ILIKE '%ACCION CRUZA%')
    ORDER BY
        CAMP_PROM_ID DESC

) 
,
TICKETS_TOTAL_NOABANDONO AS (

    SELECT
        DISTINCT
        TIEM_DIA_ID,
        VNTA_COD_DESCUENTO,
        TICKET,
        CAMP_PROM_ID,
        CAMP_PROM_NOMBRE,
        CAMP_PROM_ESPECIFICACION,
        CAMP_PROM_FINI,
        CAMP_PROM_FFIN,
        CAMP_PROM_UNNG,
        CAMP_PROM_CANAL,
        B.VNTA_CODIGO_PROMOCION
    FROM
        MSTRDB.DWH.FT_VENTAS_DESCUENTOS_LINEAS A
         INNER JOIN PROMOCIONES_FOCO_NOABANDONO B ON (
                A.VNTA_COD_DESCUENTO::VARCHAR = B.VNTA_CODIGO_PROMOCION 
                OR A.VNTA_CODIGO_PROMOCION::VARCHAR = B.VNTA_CODIGO_PROMOCION
                OR A.VNTA_CODIGO::VARCHAR = B.VNTA_CODIGO_PROMOCION
                OR A.VNTA_COD_DESCUENTO::VARCHAR = B.GEO_PROMOTION AND B.GEO_PROMOTION IS NOT NULL
                OR A.VNTA_CODIGO_PROMOCION::VARCHAR = B.GEO_PROMOTION AND B.GEO_PROMOTION IS NOT NULL
                OR A.VNTA_CODIGO::VARCHAR = B.GEO_PROMOTION AND B.GEO_PROMOTION IS NOT NULL
            ) AND A.TIEM_DIA_ID BETWEEN B.CAMP_PROM_FINI AND B.CAMP_PROM_FFIN
    WHERE
        YEAR(TIEM_DIA_ID) >= YEAR(CURRENT_DATE) - 1

) 
,
ACCIONES_FOCO_GENERAL AS (
    SELECT
        'ACCIONES FOCO' AS ACCION,
        'REACTIVACION CLIENTES' AS OBJETIVO,
        YEAR(FV.TIEM_DIA_ID) ANIO,
        MONTH(FV.TIEM_DIA_ID) AS MES,
        COUNT(DISTINCT(FV.TICKET)) AS TICKETS,
        ROUND(SUM(FV.VNTA_IMPORTE_SIN_IVA)) AS VTA_PROMO,
        ROUND(SUM(FV.VNTA_IMPORTE_SIN_IVA - (FV.VNTA_UNIDADES * FV.VNTA_COSTO_PROM_POND))) AS GB1_PROMO,
        ROUND(GB1_PROMO / VTA_PROMO, 2) AS MARGEN_PROMO,
        COUNT(DISTINCT(FFM.SOCI_SOCI_ID)) AS SOCIOS_CON_PROMO
    FROM
        MSTRDB.DWH.FT_VENTAS AS FV
        INNER JOIN MSTRDB.DWH.LU_ARTC_ARTICULO AS LAA ON FV.ARTC_ARTC_ID = LAA.ARTC_ARTC_ID
        LEFT JOIN MSTRDB.DWH.FT_VENTAS_RESUMEN_DESCUENTOS AS VRD ON FV.TICKET = VRD.TICKET AND FV.ARTC_ARTC_ID = VRD.ARTC_ARTC_ID AND VRD.VNTA_COD_DESCUENTO IN (SELECT DISTINCT VNTA_CODIGO_PROMOCION FROM PROMOCIONES_FOCO_NOABANDONO)
        INNER JOIN MSTRDB.DWH.FT_FDLN_MOVIMIENTOS AS FFM ON FV.TICKET = FFM.TICKET AND FV.TIEM_DIA_ID = FFM.TIEM_DIA_ID
        INNER JOIN PROMOCIONES_FOCO_NOABANDONO AS PFN ON VRD.VNTA_COD_DESCUENTO = PFN.VNTA_CODIGO_PROMOCION
    WHERE
        YEAR(FV.TIEM_DIA_ID) >= YEAR(CURRENT_DATE) - 1
        AND FFM.FDLN_MOVT_TIPO = 'RP'
        AND FV.TICKET IN (SELECT DISTINCT TICKET FROM TICKETS_TOTAL_NOABANDONO)
        AND VRD.VNTA_COD_DESCUENTO IS NOT NULL
    GROUP BY
        ALL
ORDER BY
    1 DESC,
    2,
    3
) 
,

CUPONES_SEGMENTADOS AS (

    SELECT
        CAMP_PROM_ID,
        COALESCE(PAZOS_CODIGO_PROMO, VNTA_CODIGO_PROMOCION) AS VNTA_CODIGO_PROMOCION,
        GEO_PROMOTION,
        CAMP_PROM_FINI,
        CAMP_PROM_FFIN,
        CAMP_PROM_UNNG,
        CAMP_PROM_TIPO,
        CAMP_PROM_NOMBRE,
        CAMP_PROM_ESPECIFICACION,
        CAMP_PROM_OBJETIVO,
        CAMP_PROM_APLICACION,
        CAMP_PROM_CANAL
    FROM
        SANDBOX_PLUS.DWH.DETALLE_PROMO AS A
        LEFT JOIN MSTRDB.DWH.LU_PROMO_RPM AS L on L.RPM_CODIGO_PROMO = A.VNTA_CODIGO_PROMOCION
    WHERE
        CAMP_PROM_OBJETIVO <> 'Informativo'
        AND YEAR(CAMP_PROM_FINI) >= YEAR(CURRENT_DATE) - 1
        AND (CAMP_PROM_NOMBRE ILIKE '%SEGMENTADO%' OR CAMP_PROM_NOMBRE ILIKE '%CUPONES APP')
    ORDER BY
        CAMP_PROM_ID DESC

) 
,
TICKETS_SEGMENTADOS AS (

    SELECT
        DISTINCT
        TIEM_DIA_ID,
        VNTA_COD_DESCUENTO,
        TICKET,
        CAMP_PROM_ID,
        CAMP_PROM_NOMBRE,
        CAMP_PROM_ESPECIFICACION,
        CAMP_PROM_FINI,
        CAMP_PROM_FFIN,
        CAMP_PROM_UNNG,
        CAMP_PROM_CANAL,
        B.VNTA_CODIGO_PROMOCION
    FROM
        MSTRDB.DWH.FT_VENTAS_DESCUENTOS_LINEAS A
         INNER JOIN CUPONES_SEGMENTADOS B ON (
                A.VNTA_COD_DESCUENTO::VARCHAR = B.VNTA_CODIGO_PROMOCION 
                OR A.VNTA_CODIGO_PROMOCION::VARCHAR = B.VNTA_CODIGO_PROMOCION
                OR A.VNTA_CODIGO::VARCHAR = B.VNTA_CODIGO_PROMOCION
                OR A.VNTA_COD_DESCUENTO::VARCHAR = B.GEO_PROMOTION AND B.GEO_PROMOTION IS NOT NULL
                OR A.VNTA_CODIGO_PROMOCION::VARCHAR = B.GEO_PROMOTION AND B.GEO_PROMOTION IS NOT NULL
                OR A.VNTA_CODIGO::VARCHAR = B.GEO_PROMOTION AND B.GEO_PROMOTION IS NOT NULL
            ) AND A.TIEM_DIA_ID BETWEEN B.CAMP_PROM_FINI AND B.CAMP_PROM_FFIN
    WHERE
        YEAR(TIEM_DIA_ID) >= YEAR(CURRENT_DATE) - 1

) 
,
ACCIONES_SEGMENTADOS AS (
    SELECT
        'SEGMENTADOS' AS ACCION,
        'CLIENTES ACTUALES' AS OBJETIVO,
        YEAR(FV.TIEM_DIA_ID) ANIO,
        MONTH(FV.TIEM_DIA_ID) AS MES,
        COUNT(DISTINCT(FV.TICKET)) AS TICKETS,
        ROUND(SUM(FV.VNTA_IMPORTE_SIN_IVA)) AS VTA_PROMO,
        ROUND(SUM(FV.VNTA_IMPORTE_SIN_IVA - (FV.VNTA_UNIDADES * FV.VNTA_COSTO_PROM_POND))) AS GB1_PROMO,
        ROUND(GB1_PROMO / VTA_PROMO, 2) AS MARGEN_PROMO,
        COUNT(DISTINCT(FFM.SOCI_SOCI_ID)) AS SOCIOS_CON_PROMO
    FROM
        MSTRDB.DWH.FT_VENTAS AS FV
        INNER JOIN MSTRDB.DWH.LU_ARTC_ARTICULO AS LAA ON FV.ARTC_ARTC_ID = LAA.ARTC_ARTC_ID
        LEFT JOIN MSTRDB.DWH.FT_VENTAS_RESUMEN_DESCUENTOS AS VRD ON FV.TICKET = VRD.TICKET AND FV.ARTC_ARTC_ID = VRD.ARTC_ARTC_ID AND VRD.VNTA_COD_DESCUENTO IN (SELECT DISTINCT VNTA_CODIGO_PROMOCION FROM CUPONES_SEGMENTADOS)
        INNER JOIN MSTRDB.DWH.FT_FDLN_MOVIMIENTOS AS FFM ON FV.TICKET = FFM.TICKET AND FV.TIEM_DIA_ID = FFM.TIEM_DIA_ID
        INNER JOIN CUPONES_SEGMENTADOS AS PFN ON VRD.VNTA_COD_DESCUENTO = PFN.VNTA_CODIGO_PROMOCION
    WHERE
        YEAR(FV.TIEM_DIA_ID) >= YEAR(CURRENT_DATE) - 1
        AND FFM.FDLN_MOVT_TIPO = 'RP'
        AND FV.TICKET IN (SELECT DISTINCT TICKET FROM TICKETS_SEGMENTADOS)
        AND VRD.VNTA_COD_DESCUENTO IS NOT NULL
    GROUP BY
        ALL
ORDER BY
    1 DESC,
    2,
    3
) 
,


CUPONES_CUMPLE AS (

    SELECT
        CAMP_PROM_ID,
        COALESCE(PAZOS_CODIGO_PROMO, VNTA_CODIGO_PROMOCION) AS VNTA_CODIGO_PROMOCION,
        GEO_PROMOTION,
        CAMP_PROM_FINI,
        CAMP_PROM_FFIN,
        CAMP_PROM_UNNG,
        CAMP_PROM_TIPO,
        CAMP_PROM_NOMBRE,
        CAMP_PROM_ESPECIFICACION,
        CAMP_PROM_OBJETIVO,
        CAMP_PROM_APLICACION,
        CAMP_PROM_CANAL
    FROM
        SANDBOX_PLUS.DWH.DETALLE_PROMO AS A
        LEFT JOIN MSTRDB.DWH.LU_PROMO_RPM AS L on L.RPM_CODIGO_PROMO = A.VNTA_CODIGO_PROMOCION
    WHERE
        CAMP_PROM_OBJETIVO <> 'Informativo'
        AND (CAMP_PROM_NOMBRE ILIKE '%CUMPL%')
        AND CAMP_PROM_ID NOT IN (20, 26)
    ORDER BY
        CAMP_PROM_ID DESC

) 
,
TICKETS_CUMPLE AS (

    SELECT
        DISTINCT
        TIEM_DIA_ID,
        VNTA_COD_DESCUENTO,
        TICKET,
        CAMP_PROM_ID,
        CAMP_PROM_NOMBRE,
        CAMP_PROM_ESPECIFICACION,
        CAMP_PROM_FINI,
        CAMP_PROM_FFIN,
        CAMP_PROM_UNNG,
        CAMP_PROM_CANAL,
        B.VNTA_CODIGO_PROMOCION
    FROM
        MSTRDB.DWH.FT_VENTAS_DESCUENTOS_LINEAS A
         INNER JOIN CUPONES_CUMPLE B ON (
                A.VNTA_COD_DESCUENTO::VARCHAR = B.VNTA_CODIGO_PROMOCION 
                OR A.VNTA_CODIGO_PROMOCION::VARCHAR = B.VNTA_CODIGO_PROMOCION
                OR A.VNTA_CODIGO::VARCHAR = B.VNTA_CODIGO_PROMOCION
                OR A.VNTA_COD_DESCUENTO::VARCHAR = B.GEO_PROMOTION AND B.GEO_PROMOTION IS NOT NULL
                OR A.VNTA_CODIGO_PROMOCION::VARCHAR = B.GEO_PROMOTION AND B.GEO_PROMOTION IS NOT NULL
                OR A.VNTA_CODIGO::VARCHAR = B.GEO_PROMOTION AND B.GEO_PROMOTION IS NOT NULL
            ) AND A.TIEM_DIA_ID BETWEEN B.CAMP_PROM_FINI AND B.CAMP_PROM_FFIN
    WHERE
        YEAR(TIEM_DIA_ID) >= YEAR(CURRENT_DATE) 

) 
,
ACCIONES_CUMPLE AS (
    SELECT
        'CUMPLE' AS ACCION,
        'CLIENTES ACTUALES' AS OBJETIVO,
        YEAR(FV.TIEM_DIA_ID) ANIO,
        MONTH(FV.TIEM_DIA_ID) AS MES,
        COUNT(DISTINCT(FV.TICKET)) AS TICKETS,
        ROUND(SUM(FV.VNTA_IMPORTE_SIN_IVA)) AS VTA_PROMO,
        ROUND(SUM(FV.VNTA_IMPORTE_SIN_IVA - (FV.VNTA_UNIDADES * FV.VNTA_COSTO_PROM_POND))) AS GB1_PROMO,
        ROUND(GB1_PROMO / VTA_PROMO, 2) AS MARGEN_PROMO,
        COUNT(DISTINCT(FFM.SOCI_SOCI_ID)) AS SOCIOS_CON_PROMO
    FROM
        MSTRDB.DWH.FT_VENTAS AS FV
        INNER JOIN MSTRDB.DWH.LU_ARTC_ARTICULO AS LAA ON FV.ARTC_ARTC_ID = LAA.ARTC_ARTC_ID
        INNER JOIN MSTRDB.DWH.FT_FDLN_MOVIMIENTOS AS FFM ON FV.TICKET = FFM.TICKET AND FV.TIEM_DIA_ID = FFM.TIEM_DIA_ID
    WHERE
        YEAR(FV.TIEM_DIA_ID) >= YEAR(CURRENT_DATE)
        AND FFM.FDLN_MOVT_TIPO = 'RP'
        AND FV.TICKET IN (SELECT DISTINCT TICKET FROM TICKETS_CUMPLE)
    GROUP BY
        ALL
ORDER BY
    1 DESC,
    2,
    3
) 

,
CUPONES_CUOTA AS (

    SELECT
        CAMP_PROM_ID,
        COALESCE(PAZOS_CODIGO_PROMO, VNTA_CODIGO_PROMOCION) AS VNTA_CODIGO_PROMOCION,
        GEO_PROMOTION,
        CAMP_PROM_FINI,
        CAMP_PROM_FFIN,
        CAMP_PROM_UNNG,
        CAMP_PROM_TIPO,
        CAMP_PROM_NOMBRE,
        CAMP_PROM_ESPECIFICACION,
        CAMP_PROM_OBJETIVO,
        CAMP_PROM_APLICACION,
        CAMP_PROM_CANAL
    FROM
        SANDBOX_PLUS.DWH.DETALLE_PROMO AS A
        LEFT JOIN MSTRDB.DWH.LU_PROMO_RPM AS L on L.RPM_CODIGO_PROMO = A.VNTA_CODIGO_PROMOCION
    WHERE
        CAMP_PROM_OBJETIVO <> 'Informativo'
        AND (CAMP_PROM_NOMBRE ILIKE '%CUOTA%')
    ORDER BY
        CAMP_PROM_ID DESC

) 
,
TICKETS_CUOTA AS (

    SELECT
        DISTINCT
        TIEM_DIA_ID,
        VNTA_COD_DESCUENTO,
        TICKET,
        CAMP_PROM_ID,
        CAMP_PROM_NOMBRE,
        CAMP_PROM_ESPECIFICACION,
        CAMP_PROM_FINI,
        CAMP_PROM_FFIN,
        CAMP_PROM_UNNG,
        CAMP_PROM_CANAL,
        B.VNTA_CODIGO_PROMOCION
    FROM
        MSTRDB.DWH.FT_VENTAS_DESCUENTOS_LINEAS A
         INNER JOIN CUPONES_CUOTA B ON (
                A.VNTA_COD_DESCUENTO::VARCHAR = B.VNTA_CODIGO_PROMOCION 
                OR A.VNTA_CODIGO_PROMOCION::VARCHAR = B.VNTA_CODIGO_PROMOCION
                OR A.VNTA_CODIGO::VARCHAR = B.VNTA_CODIGO_PROMOCION
                OR A.VNTA_COD_DESCUENTO::VARCHAR = B.GEO_PROMOTION AND B.GEO_PROMOTION IS NOT NULL
                OR A.VNTA_CODIGO_PROMOCION::VARCHAR = B.GEO_PROMOTION AND B.GEO_PROMOTION IS NOT NULL
                OR A.VNTA_CODIGO::VARCHAR = B.GEO_PROMOTION AND B.GEO_PROMOTION IS NOT NULL
            ) AND A.TIEM_DIA_ID BETWEEN B.CAMP_PROM_FINI AND B.CAMP_PROM_FFIN
    WHERE
        YEAR(TIEM_DIA_ID) >= YEAR(CURRENT_DATE) 

) 
,
ACCIONES_CUOTA AS (
    SELECT
        'CUOTA' AS ACCION,
        'CLIENTES ACTUALES' AS OBJETIVO,
        YEAR(FV.TIEM_DIA_ID) ANIO,
        MONTH(FV.TIEM_DIA_ID) AS MES,
        COUNT(DISTINCT(FV.TICKET)) AS TICKETS,
        ROUND(SUM(FV.VNTA_IMPORTE_SIN_IVA)) AS VTA_PROMO,
        ROUND(SUM(FV.VNTA_IMPORTE_SIN_IVA - (FV.VNTA_UNIDADES * FV.VNTA_COSTO_PROM_POND))) AS GB1_PROMO,
        ROUND(GB1_PROMO / VTA_PROMO, 2) AS MARGEN_PROMO,
        COUNT(DISTINCT(FFM.SOCI_SOCI_ID)) AS SOCIOS_CON_PROMO
    FROM
        MSTRDB.DWH.FT_VENTAS AS FV
        INNER JOIN MSTRDB.DWH.LU_ARTC_ARTICULO AS LAA ON FV.ARTC_ARTC_ID = LAA.ARTC_ARTC_ID
        INNER JOIN MSTRDB.DWH.FT_FDLN_MOVIMIENTOS AS FFM ON FV.TICKET = FFM.TICKET AND FV.TIEM_DIA_ID = FFM.TIEM_DIA_ID
    WHERE
        YEAR(FV.TIEM_DIA_ID) >= YEAR(CURRENT_DATE)
        AND FFM.FDLN_MOVT_TIPO = 'RP'
        AND FV.TICKET IN (SELECT DISTINCT TICKET FROM TICKETS_CUOTA)
    GROUP BY
        ALL
ORDER BY
    1 DESC,
    2,
    3
) 

,
MARCA_PROPIA AS (

    SELECT
        CAMP_PROM_ID,
        COALESCE(PAZOS_CODIGO_PROMO, VNTA_CODIGO_PROMOCION) AS VNTA_CODIGO_PROMOCION,
        GEO_PROMOTION,
        CAMP_PROM_FINI,
        CAMP_PROM_FFIN,
        CAMP_PROM_UNNG,
        CAMP_PROM_TIPO,
        CAMP_PROM_NOMBRE,
        CAMP_PROM_ESPECIFICACION,
        CAMP_PROM_OBJETIVO,
        CAMP_PROM_APLICACION,
        CAMP_PROM_CANAL
    FROM
        SANDBOX_PLUS.DWH.DETALLE_PROMO AS A
        LEFT JOIN MSTRDB.DWH.LU_PROMO_RPM AS L on L.RPM_CODIGO_PROMO = A.VNTA_CODIGO_PROMOCION
    WHERE
        CAMP_PROM_OBJETIVO <> 'Informativo'
        AND (CAMP_PROM_NOMBRE ILIKE '%MARCA PROPIA%')
    ORDER BY
        CAMP_PROM_ID DESC

) 
,
TICKETS_MP AS (

    SELECT
        DISTINCT
        TIEM_DIA_ID,
        VNTA_COD_DESCUENTO,
        TICKET,
        CAMP_PROM_ID,
        CAMP_PROM_NOMBRE,
        CAMP_PROM_ESPECIFICACION,
        CAMP_PROM_FINI,
        CAMP_PROM_FFIN,
        CAMP_PROM_UNNG,
        CAMP_PROM_CANAL,
        B.VNTA_CODIGO_PROMOCION
    FROM
        MSTRDB.DWH.FT_VENTAS_DESCUENTOS_LINEAS A
         INNER JOIN MARCA_PROPIA B ON (
                A.VNTA_COD_DESCUENTO::VARCHAR = B.VNTA_CODIGO_PROMOCION 
                OR A.VNTA_CODIGO_PROMOCION::VARCHAR = B.VNTA_CODIGO_PROMOCION
                OR A.VNTA_CODIGO::VARCHAR = B.VNTA_CODIGO_PROMOCION
                OR A.VNTA_COD_DESCUENTO::VARCHAR = B.GEO_PROMOTION AND B.GEO_PROMOTION IS NOT NULL
                OR A.VNTA_CODIGO_PROMOCION::VARCHAR = B.GEO_PROMOTION AND B.GEO_PROMOTION IS NOT NULL
                OR A.VNTA_CODIGO::VARCHAR = B.GEO_PROMOTION AND B.GEO_PROMOTION IS NOT NULL
            ) AND A.TIEM_DIA_ID BETWEEN B.CAMP_PROM_FINI AND B.CAMP_PROM_FFIN
    WHERE
        YEAR(TIEM_DIA_ID) >= YEAR(CURRENT_DATE) 

) 
,
ACCIONES_MP AS (
    SELECT
        'MARCA PROPIA' AS ACCION,
        'CLIENTES ACTUALES' AS OBJETIVO,
        YEAR(FV.TIEM_DIA_ID) ANIO,
        MONTH(FV.TIEM_DIA_ID) AS MES,
        COUNT(DISTINCT(FV.TICKET)) AS TICKETS,
        ROUND(SUM(FV.VNTA_IMPORTE_SIN_IVA)) AS VTA_PROMO,
        ROUND(SUM(FV.VNTA_IMPORTE_SIN_IVA - (FV.VNTA_UNIDADES * FV.VNTA_COSTO_PROM_POND))) AS GB1_PROMO,
        ROUND(GB1_PROMO / VTA_PROMO, 2) AS MARGEN_PROMO,
        COUNT(DISTINCT(FFM.SOCI_SOCI_ID)) AS SOCIOS_CON_PROMO
    FROM
        MSTRDB.DWH.FT_VENTAS AS FV
        INNER JOIN MSTRDB.DWH.LU_ARTC_ARTICULO AS LAA ON FV.ARTC_ARTC_ID = LAA.ARTC_ARTC_ID
        LEFT JOIN MSTRDB.DWH.FT_VENTAS_RESUMEN_DESCUENTOS AS VRD ON FV.TICKET = VRD.TICKET AND FV.ARTC_ARTC_ID = VRD.ARTC_ARTC_ID AND VRD.VNTA_COD_DESCUENTO IN (SELECT DISTINCT VNTA_CODIGO_PROMOCION FROM MARCA_PROPIA)
        INNER JOIN MSTRDB.DWH.FT_FDLN_MOVIMIENTOS AS FFM ON FV.TICKET = FFM.TICKET AND FV.TIEM_DIA_ID = FFM.TIEM_DIA_ID
        INNER JOIN MARCA_PROPIA AS PFN ON VRD.VNTA_COD_DESCUENTO = PFN.VNTA_CODIGO_PROMOCION
    WHERE
        YEAR(FV.TIEM_DIA_ID) >= YEAR(CURRENT_DATE) - 1
        AND FFM.FDLN_MOVT_TIPO = 'RP'
        AND FV.TICKET IN (SELECT DISTINCT TICKET FROM TICKETS_MP)
        AND VRD.VNTA_COD_DESCUENTO IS NOT NULL
    GROUP BY
        ALL
ORDER BY
    1 DESC,
    2,
    3

) 


SELECT
    OBJETIVO,
    ANIO,
    MES,
    SUM(TICKETS) AS TICKETS,
    SUM(VTA_PROMO) AS VTA_PROMO,
    SUM(GB1_PROMO) AS GB1_PROMO,
    SUM(SOCIOS_CON_PROMO) AS CLIENTES_USO,
FROM
    (
    (SELECT * FROM ACCIONES_SEGMENTADOS)
    UNION ALL
    (SELECT * FROM ACCIONES_FOCO_GENERAL)
    UNION ALL
    (SELECT * FROM ACCION_ABANDONO_TOTAL)
    UNION ALL
    (SELECT * FROM ACCIONES_CUMPLE)
    UNION ALL
    (SELECT * FROM ACCIONES_CUOTA)
    UNION ALL
    (SELECT * FROM ACCIONES_MP)
    )
WHERE
    ANIO >= 2025
GROUP BY
    ALL
ORDER BY
    2,
    3,
    1;
