
  WITH COMPRAS_DIA AS (
    SELECT
        DOCUMENT_NUMBER,
        TRANSACTION_DATE,
        MAX(CASE WHEN BRANCH_NAME = 'BAS' THEN 'BAS'
                 WHEN BRANCH_NAME = 'TATA' THEN 'TATA'
                 ELSE NULL END) AS UN_COMPRA
    FROM MSTRDB.NPL.MOVEMENTS
    WHERE MOVEMENT_TYPE = 'EARN'
    GROUP BY 1, 2
),
SOCIOS_ESTADO AS (
    SELECT
        DATE(UPDATE_DATE) AS FECHA,
        STATUS,
        ID,
        DOCUMENT_NUMBER
    FROM MSTRDB.NPL.MEMBERS
    WHERE DATE(UPDATE_DATE) > '2024-11-14'
)
SELECT
    S.FECHA AS FECHA_REGISTRO,
    COALESCE(C.UN_COMPRA, 'PLUS') AS ATRIBUCION,
    COUNT(DISTINCT CASE WHEN S.STATUS = 'ACTIVE' THEN S.ID END) AS ACTIVOS,
    
FROM SOCIOS_ESTADO S
LEFT JOIN COMPRAS_DIA C ON S.DOCUMENT_NUMBER = C.DOCUMENT_NUMBER AND S.FECHA = C.TRANSACTION_DATE
GROUP BY 1, 2
ORDER BY 1 DESC, 2 ASC