

WITH FECHAS AS (
    SELECT
        DATE_TRUNC('MONTH', CURRENT_DATE)                   AS inicio_anio_actual,    
        CURRENT_DATE - 1                                    AS fin_anio_actual,        
        ADD_MONTHS(DATE_TRUNC('MONTH', CURRENT_DATE), -12)  AS inicio_anio_anterior,   
        ADD_MONTHS(CURRENT_DATE - 1, -12)                  AS fin_anio_anterior       

)
,
FIDELIZACION AS (
    SELECT
        YEAR(FV.TIEM_DIA_ID) AS ANIO,
        LGD.GEOG_DPTO_DESC AS DEPARTAMENTO,
        LGL.GEOG_LOCL_COD AS LOCAL,
        LGL.GEOG_LOCL_DESC AS DESCRIPCION_LOCAL,
        FV.TICKET,
        CASE WHEN FFM.TICKET IS NOT NULL THEN FFM.TICKET ELSE NULL END AS TICKET_FIDELIZADO,
        CASE WHEN FFM.TICKET IS NOT NULL THEN FFM.SOCI_SOCI_ID ELSE NULL END AS SOCIO
    FROM  
        MSTRDB.DWH.FT_VENTAS AS FV
        LEFT JOIN MSTRDB.DWH.FT_FDLN_MOVIMIENTOS AS FFM ON FV.TICKET = FFM.TICKET AND FFM.FDLN_MOVT_TIPO = 'RP'
        INNER JOIN MSTRDB.DWH.LU_GEOG_LOCAL AS LGL ON FV.GEOG_LOCL_ID = LGL.GEOG_LOCL_ID AND LGL.GEOG_UNNG_ID = 2
        INNER JOIN MSTRDB.DWH.LU_GEOG_DEPTO AS LGD ON LGL.GEOG_DPTO_ID = LGD.GEOG_DPTO_ID
        JOIN FECHAS AS F
    WHERE   
        (FV.TIEM_DIA_ID BETWEEN F.inicio_anio_actual AND F.fin_anio_actual OR FV.TIEM_DIA_ID BETWEEN F.inicio_anio_anterior AND F.fin_anio_anterior)
    GROUP BY
        ALL
    ORDER BY
        1
) 
,
FIDELIZACION_2 AS (
    SELECT
        ANIO,
        LOCAL,
        DESCRIPCION_LOCAL,
        DEPARTAMENTO,
        COUNT(DISTINCT(TICKET)) AS TICKETS_GENERALES_TATA,
        COUNT(DISTINCT(TICKET_FIDELIZADO)) AS TICKETS_FIDELIZADOS,
        ROUND((TICKETS_FIDELIZADOS / TICKETS_GENERALES_TATA) * 100, 2) AS PORCENTAJE_FIDELIZACION,
        COUNT(DISTINCT(SOCIO)) AS SOCIOS
    FROM
        FIDELIZACION
    GROUP BY
        ALL
    ORDER BY
        2, 1
) 
SELECT
    *
FROM
    FIDELIZACION_2;