WITH FECHAS AS (

    SELECT 
        YEAR(CURRENT_DATE) AS A_ACTUAL, 
        YEAR(DATEADD(YEAR, -1, CURRENT_DATE)) AS A_ANTERIOR, 
        DAY(CURRENT_DATE - 1) AS HASTA, 
        MONTH(CURRENT_DATE) AS MES_ACTUAL,
        DAY(DATE_TRUNC(MONTH, CURRENT_DATE())) AS DESDE

) 
,

TATA_FISICO AS (

    SELECT 
        YEAR(FFM.TIEM_DIA_ID) AS ANIO,
        MONTH(FFM.TIEM_DIA_ID) AS MES,
        LGL.GEOG_LOCL_COD AS LOCAL,
        LGL.GEOG_LOCL_DESC AS DESCRIPCION_LOCAL,
        LGD.GEOG_DPTO_DESC AS DEPARTAMENTO,
        FFM.SOCI_SOCI_ID AS SOCIO
    FROM 
        MSTRDB.DWH.FT_FDLN_MOVIMIENTOS AS FFM
        INNER JOIN MSTRDB.DWH.FT_VENTAS AS FV ON FFM.TICKET = FV.TICKET
        INNER JOIN MSTRDB.DWH.LU_GEOG_LOCAL AS LGL ON LGL.GEOG_LOCL_ID = FFM.GEOG_LOCL_ID
        INNER JOIN MSTRDB.DWH.LU_GEOG_DEPTO AS LGD ON LGL.GEOG_DPTO_ID = LGD.GEOG_DPTO_ID
        JOIN FECHAS AS F
    WHERE 
        YEAR(FFM.TIEM_DIA_ID) IN (F.A_ACTUAL, F.A_ANTERIOR)
        AND MONTH(FFM.TIEM_DIA_ID) = F.MES_ACTUAL
        AND DAY(FFM.TIEM_DIA_ID) <= F.HASTA
        AND FFM.FDLN_MOVT_TIPO = 'RP'
        AND FFM.GEOG_LOCL_ID IN (SELECT DISTINCT GEOG_LOCL_ID FROM MSTRDB.DWH.LU_GEOG_LOCAL WHERE GEOG_UNNG_ID = 2)
        
) 
,
ECOMMERCE AS (

    SELECT
        YEAR(TRANSACTION_DATE) AS ANIO,
        MONTH(TRANSACTION_DATE) AS MES,
        BRANCH_ID AS LOCAL,
        BRANCH_NAME AS DESCRIPCION_LOCAL,
        'ECOMMERCE' AS DEPARTAMENTO,
        B.SOCI_SOCI_ID AS SOCIO
    FROM
        MSTRDB.NPL.MOVEMENTS AS A
        INNER JOIN MSTRDB.DWH.LU_CLIE_CLIENTE AS B ON A.DOCUMENT_TYPE = B.CLIE_TIPO_DOC AND A.DOCUMENT_NUMBER = B.CLIE_CLIE_NDOC
        JOIN FECHAS AS F
    WHERE
        A.MOVEMENT_TYPE = 'EARN'
        AND A.BRANCH_ID = 198
        AND YEAR(TRANSACTION_DATE) IN (F.A_ACTUAL, F.A_ANTERIOR)
        AND MONTH(TRANSACTION_DATE) = F.MES_ACTUAL
        AND DAY(TRANSACTION_DATE) <= F.HASTA

) 
,
OMNICANAL AS (
    SELECT 
        ANIO,
        MES,
        CAST(LOCAL AS NUMBER) AS LOCAL,
        DESCRIPCION_LOCAL,
        DEPARTAMENTO,
        SOCIO
    FROM
        (
        (SELECT * FROM TATA_FISICO)
        UNION ALL
        (SELECT * FROM ECOMMERCE)
        )
    
) 
,
CLIENTES AS (
    SELECT
        'TATA' AS UNNG,
        ANIO,
        DEPARTAMENTO,
        COUNT(DISTINCT(SOCIO)) AS SOCIOS,
        SOCIOS - LAG(SOCIOS) OVER (PARTITION BY DEPARTAMENTO ORDER BY ANIO) AS VARIACION_ABS,
        ROUND(
            (SOCIOS - LAG(SOCIOS) OVER (PARTITION BY DEPARTAMENTO ORDER BY ANIO)) / NULLIF(LAG(SOCIOS) OVER (PARTITION BY DEPARTAMENTO ORDER BY ANIO), 0) * 100, 2
        ) AS VARIACION_PCT
    FROM
        OMNICANAL
    GROUP BY
        ALL

) 
SELECT * FROM CLIENTES;
