WITH FECHAS AS (

    SELECT 
        YEAR(CURRENT_DATE) AS A_ACTUAL, 
        YEAR(DATEADD(YEAR, -1, CURRENT_DATE)) AS A_ANTERIOR, 
        DAY(CURRENT_DATE - 1) AS HASTA, 
        MONTH(CURRENT_DATE) AS MES_ACTUAL,
        DAY(DATE_TRUNC(MONTH, CURRENT_DATE())) AS DESDE

) --SELECT * FROM FECHAS;
,

TATA_FISICO AS (

    SELECT 
        YEAR(FFM.TIEM_DIA_ID) AS ANIO,
        MONTH(FFM.TIEM_DIA_ID) AS MES,
        LGL.GEOG_LOCL_COD AS LOCAL,
        LGL.GEOG_LOCL_DESC AS DESCRIPCION_LOCAL,
        LGD.GEOG_DPTO_DESC AS DEPARTAMENTO,
        FFM.SOCI_SOCI_ID AS SOCIO
    FROM 
        MSTRDB.DWH.FT_FDLN_MOVIMIENTOS AS FFM
        INNER JOIN MSTRDB.DWH.FT_VENTAS AS FV ON FFM.TICKET = FV.TICKET
        INNER JOIN MSTRDB.DWH.LU_GEOG_LOCAL AS LGL ON LGL.GEOG_LOCL_ID = FFM.GEOG_LOCL_ID
        INNER JOIN MSTRDB.DWH.LU_GEOG_DEPTO AS LGD ON LGL.GEOG_DPTO_ID = LGD.GEOG_DPTO_ID
        JOIN FECHAS AS F
    WHERE 
        YEAR(FFM.TIEM_DIA_ID) IN (F.A_ACTUAL, F.A_ANTERIOR)
        AND FFM.TIEM_DIA_ID < DATE_TRUNC(MONTH, CURRENT_DATE())
        AND FFM.FDLN_MOVT_TIPO = 'RP'
        AND FFM.GEOG_LOCL_ID IN (SELECT DISTINCT GEOG_LOCL_ID FROM MSTRDB.DWH.LU_GEOG_LOCAL WHERE GEOG_UNNG_ID = 2)
        
) --SELECT * FROM TATA_FISICO;
,
ECOMMERCE AS (

    SELECT
        YEAR(TRANSACTION_DATE) AS ANIO,
        MONTH(TRANSACTION_DATE) AS MES,
        BRANCH_ID AS LOCAL,
        BRANCH_NAME AS DESCRIPCION_LOCAL,
        'ECOMMERCE' AS DEPARTAMENTO,
        B.SOCI_SOCI_ID AS SOCIO
    FROM
        MSTRDB.NPL.MOVEMENTS AS A
        INNER JOIN MSTRDB.DWH.LU_CLIE_CLIENTE AS B ON A.DOCUMENT_TYPE = B.CLIE_TIPO_DOC AND A.DOCUMENT_NUMBER = B.CLIE_CLIE_NDOC
        JOIN FECHAS AS F
    WHERE
        A.MOVEMENT_TYPE = 'EARN'
        AND A.BRANCH_ID = 198
        AND YEAR(TRANSACTION_DATE) IN (F.A_ACTUAL, F.A_ANTERIOR)
        AND TRANSACTION_DATE < DATE_TRUNC(MONTH, CURRENT_DATE())

) --SELECT * FROM ECOMMERCE;
,
OMNICANAL AS (
    SELECT 
        ANIO,
        MES,
        CAST(LOCAL AS NUMBER) AS LOCAL,
        DESCRIPCION_LOCAL,
        DEPARTAMENTO,
        SOCIO
    FROM
        (
        (SELECT * FROM TATA_FISICO)
        UNION ALL
        (SELECT * FROM ECOMMERCE)
        )
    
) --SELECT * FROM OMNICANAL;
,
CLIENTES AS (
    SELECT
        'TATA' AS UNNG,
        ANIO,
        MES,
        DEPARTAMENTO,
        COUNT(DISTINCT(SOCIO)) AS SOCIOS,
        SOCIOS - LAG(SOCIOS) OVER (PARTITION BY DEPARTAMENTO, MES ORDER BY MES, ANIO) AS VARIACION_ABS,
        ROUND(
            (SOCIOS - LAG(SOCIOS) OVER (PARTITION BY DEPARTAMENTO, MES ORDER BY MES, ANIO)) / NULLIF(LAG(SOCIOS) OVER (PARTITION BY DEPARTAMENTO, MES ORDER BY MES, ANIO), 0) * 100, 2
        ) AS VARIACION_PCT
    FROM
        OMNICANAL
    GROUP BY
        ALL

) 
-------------------------
--SELECT * FROM CLIENTES ORDER BY 4, 3, 2;
-------------------------

-------------------------------------------------------------- FIDELIZACION POR DEPARTAMENTO ------------------------------------------------------------
--------------------------------------------------------------------- PESTAÑA MAPA ----------------------------------------------------------------------

,
FIDELIZACION AS (
    SELECT
        YEAR(FV.TIEM_DIA_ID) AS ANIO,
        MONTH(FV.TIEM_DIA_ID) AS MES,
        LGD.GEOG_DPTO_DESC AS DEPARTAMENTO,
        LGL.GEOG_LOCL_COD AS LOCAL,
        LGL.GEOG_LOCL_DESC AS DESCRIPCION_LOCAL,
        FV.TICKET,
        CASE WHEN FFM.TICKET IS NOT NULL THEN FFM.TICKET ELSE NULL END AS TICKET_FIDELIZADO,
        CASE WHEN FFM.TICKET IS NOT NULL THEN FFM.SOCI_SOCI_ID ELSE NULL END AS SOCIO
    FROM  
        MSTRDB.DWH.FT_VENTAS AS FV
        LEFT JOIN MSTRDB.DWH.FT_FDLN_MOVIMIENTOS AS FFM ON FV.TICKET = FFM.TICKET AND FFM.FDLN_MOVT_TIPO = 'RP'
        INNER JOIN MSTRDB.DWH.LU_GEOG_LOCAL AS LGL ON FV.GEOG_LOCL_ID = LGL.GEOG_LOCL_ID AND LGL.GEOG_UNNG_ID = 2
        INNER JOIN MSTRDB.DWH.LU_GEOG_DEPTO AS LGD ON LGL.GEOG_DPTO_ID = LGD.GEOG_DPTO_ID
        JOIN FECHAS AS F
    WHERE   
        YEAR(FV.TIEM_DIA_ID) >= F.A_ANTERIOR
    GROUP BY
        ALL
    ORDER BY
        1
) 
,
FIDELIZACION_2 AS (
    SELECT
        ANIO,
        MES,
        LOCAL,
        DESCRIPCION_LOCAL,
        DEPARTAMENTO,
        COUNT(DISTINCT(TICKET)) AS TICKETS_GENERALES_TATA,
        COUNT(DISTINCT(TICKET_FIDELIZADO)) AS TICKETS_FIDELIZADOS,
        ROUND((TICKETS_FIDELIZADOS / TICKETS_GENERALES_TATA) * 100, 2) AS PORCENTAJE_FIDELIZACION,
        COUNT(DISTINCT(SOCIO)) AS SOCIOS
    FROM
        FIDELIZACION
    GROUP BY
        ALL
    ORDER BY
        2, 1
) 
SELECT
    *
FROM
    FIDELIZACION_2;